# Generated by Django 5.2.12 on 2026-05-07 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AutenticacionySeguridad', '0013_alter_rol_nombre'),
        ('GestionInventarioProveedores', '0003_enforce_not_null_veterinaria'),
        ('GestionServiciosyReserva', '0005_enforce_not_null_veterinaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('direccion_entrega', models.TextField(blank=True, null=True)),
                ('tipo_entrega', models.CharField(choices=[('DOMICILIO', 'Domicilio'), ('RECOJO', 'Recojo en veterinaria')], default='DOMICILIO', max_length=30)),
                ('estado_pedido', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('EN_PREPARACION', 'En preparacion'), ('EN_CAMINO', 'En camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
                ('veterinaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='AutenticacionySeguridad.veterinaria')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='GestionInventarioProveedores.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='NotificacionesySeguimiento.pedido')),
            ],
            options={
                'db_table': 'detalle_pedido',
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id_seguimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_seguimiento', models.CharField(choices=[('CITA', 'Cita'), ('SERVICIO', 'Servicio'), ('PEDIDO', 'Pedido')], max_length=30)),
                ('estado_anterior', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_actual', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('visible_cliente', models.BooleanField(default=True)),
                ('estado', models.BooleanField(default=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='GestionServiciosyReserva.cita')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='NotificacionesySeguimiento.pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos', to=settings.AUTH_USER_MODEL)),
                ('veterinaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos', to='AutenticacionySeguridad.veterinaria')),
            ],
            options={
                'db_table': 'seguimiento',
            },
        ),
    ]
