# Generated by Django 5.2.12 on 2026-05-04 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionySeguridad', '0005_reset_primary_key_sequences'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('limite_usuarios', models.IntegerField(default=0)),
                ('limite_mascotas', models.IntegerField(default=0)),
                ('permite_app_movil', models.BooleanField(default=False)),
                ('permite_reportes', models.BooleanField(default=False)),
                ('permite_backup', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan de suscripción',
                'verbose_name_plural': 'Planes de suscripción',
                'db_table': 'plan_suscripcion',
            },
        ),
        migrations.CreateModel(
            name='Veterinaria',
            fields=[
                ('id_veterinaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('nit', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Veterinaria',
                'verbose_name_plural': 'Veterinarias',
                'db_table': 'veterinaria',
            },
        ),
        migrations.AlterModelOptions(
            name='bitacora',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Bitacora', 'verbose_name_plural': 'Bitacora'},
        ),
        migrations.AddField(
            model_name='bitacora',
            name='payload',
            field=models.BinaryField(blank=True, help_text='Payload confidencial cifrado para bitacora extendida.', null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FALLIDO', 'Inicio de sesión fallido'), ('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('VISUALIZAR', 'Visualizar'), ('EXPORTAR', 'Exportar'), ('CAMBIO_PASSWORD', 'Cambio de contraseña'), ('CAMBIO_PERMISOS', 'Cambio de permisos'), ('ACCESO_DENEGADO', 'Acceso denegado'), ('ACTIVAR', 'Activar'), ('DESACTIVAR', 'Desactivar')], help_text='Accion realizada en el sistema.', max_length=50),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripcion legible del evento.'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_hora', help_text='Fecha y hora en que ocurrio el evento.'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='ip',
            field=models.GenericIPAddressField(blank=True, help_text='Direccion IP desde donde se origino la accion.', null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='metadatos',
            field=models.JSONField(blank=True, default=dict, help_text='Informacion adicional del evento en formato JSON.'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='modulo',
            field=models.CharField(blank=True, choices=[('autenticacion', 'Autenticación'), ('usuarios', 'Usuarios'), ('perfiles', 'Perfiles'), ('roles', 'Roles'), ('permisos', 'Permisos'), ('bitacora', 'Bitácora'), ('clientes', 'Clientes'), ('mascotas', 'Mascotas'), ('catalogos', 'Catálogos'), ('servicios', 'Servicios'), ('precios', 'Precios'), ('citas', 'Citas'), ('sistema', 'Sistema')], default='sistema', help_text='Modulo del sistema donde ocurrio el evento.', max_length=100),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='user_agent',
            field=models.TextField(blank=True, default='', help_text='Informacion del navegador o cliente.'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', help_text='Usuario que ejecuto la accion. Puede ser nulo para eventos del sistema o anonimos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ComponenteSistema',
            fields=[
                ('id_componente', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=120, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('MODULO', 'Modulo'), ('MENU', 'Menu'), ('FORMULARIO', 'Formulario'), ('BOTON', 'Boton'), ('CAMPO', 'Campo'), ('LABEL', 'Label'), ('TEXTO', 'Texto'), ('ACCION', 'Accion')], max_length=20)),
                ('modulo', models.CharField(blank=True, max_length=120, null=True)),
                ('ruta', models.CharField(blank=True, max_length=255, null=True)),
                ('plataforma', models.CharField(choices=[('WEB', 'Web'), ('MOVIL', 'Movil'), ('AMBOS', 'Ambos')], default='WEB', max_length=10)),
                ('orden', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, db_column='id_padre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='AutenticacionySeguridad.componentesistema')),
            ],
            options={
                'verbose_name': 'Componente del sistema',
                'verbose_name_plural': 'Componentes del sistema',
                'db_table': 'componente_sistema',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id_suscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado_suscripcion', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('SUSPENDIDA', 'Suspendida'), ('CANCELADA', 'Cancelada'), ('PRUEBA', 'Prueba')], default='PRUEBA', max_length=20)),
                ('renovacion_automatica', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='AutenticacionySeguridad.plansuscripcion')),
                ('veterinaria', models.ForeignKey(db_column='id_veterinaria', on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='AutenticacionySeguridad.veterinaria')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'db_table': 'suscripcion',
            },
        ),
        migrations.CreateModel(
            name='GrupoUsuario',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('veterinaria', models.ForeignKey(blank=True, db_column='id_veterinaria', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos_usuario', to='AutenticacionySeguridad.veterinaria')),
            ],
            options={
                'verbose_name': 'Grupo de usuario',
                'verbose_name_plural': 'Grupos de usuario',
                'db_table': 'grupo_usuario',
            },
        ),
        migrations.CreateModel(
            name='BackupRestore',
            fields=[
                ('id_backup_restore', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('BACKUP', 'Backup'), ('RESTORE', 'Restore')], max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('proveedor_almacenamiento', models.CharField(blank=True, max_length=80, null=True)),
                ('estado', models.CharField(choices=[('INICIADO', 'Iniciado'), ('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido')], default='INICIADO', max_length=20)),
                ('hash_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='backups_restore', to=settings.AUTH_USER_MODEL)),
                ('veterinaria', models.ForeignKey(blank=True, db_column='id_veterinaria', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backups_restore', to='AutenticacionySeguridad.veterinaria')),
            ],
            options={
                'verbose_name': 'Backup restore',
                'verbose_name_plural': 'Backups restore',
                'db_table': 'backup_restore',
            },
        ),
        migrations.AddField(
            model_name='bitacora',
            name='veterinaria',
            field=models.ForeignKey(blank=True, db_column='id_veterinaria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='AutenticacionySeguridad.veterinaria'),
        ),
        migrations.AddField(
            model_name='user',
            name='veterinaria',
            field=models.ForeignKey(blank=True, db_column='id_veterinaria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='AutenticacionySeguridad.veterinaria'),
        ),
        migrations.CreateModel(
            name='GrupoPermisoComponente',
            fields=[
                ('id_permiso_componente', models.AutoField(primary_key=True, serialize=False)),
                ('puede_ver', models.BooleanField(default=False)),
                ('puede_crear', models.BooleanField(default=False)),
                ('puede_editar', models.BooleanField(default=False)),
                ('puede_eliminar', models.BooleanField(default=False)),
                ('puede_exportar', models.BooleanField(default=False)),
                ('puede_ejecutar', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('componente', models.ForeignKey(db_column='id_componente', on_delete=django.db.models.deletion.CASCADE, related_name='permisos_grupo', to='AutenticacionySeguridad.componentesistema')),
                ('grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, related_name='permisos_componentes', to='AutenticacionySeguridad.grupousuario')),
            ],
            options={
                'verbose_name': 'Permiso de grupo por componente',
                'verbose_name_plural': 'Permisos de grupo por componente',
                'db_table': 'grupo_permiso_componente',
                'unique_together': {('grupo', 'componente')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioGrupo',
            fields=[
                ('id_usuario_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='AutenticacionySeguridad.grupousuario')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='grupos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario grupo',
                'verbose_name_plural': 'Usuarios grupo',
                'db_table': 'usuario_grupo',
                'unique_together': {('usuario', 'grupo')},
            },
        ),
    ]
