# Generated by Django 5.2.12 on 2026-05-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionySeguridad', '0009_minimize_bitacora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_hora'),
        ),
    ]
