# Generated by Django 5.2.12 on 2026-05-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionySeguridad', '0012_alter_bitacora_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadministrador'), ('ADMIN', 'Administrador'), ('VETERINARIAN', 'Veterinario'), ('RECEPCIONISTA', 'Recepcionista'), ('CLIENT', 'Cliente')], max_length=50, unique=True),
        ),
    ]
