# Generated by Django 5.2.12 on 2026-05-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionySeguridad', '0019_backupconfig_minuto_ejecucion_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupconfig',
            name='minuto_ejecucion',
            field=models.IntegerField(default=15, help_text='Minuto del día 0-59'),
        ),
    ]
