# Generated by Django 5.2.12 on 2026-05-14 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionySeguridad', '0020_alter_backupconfig_minuto_ejecucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupousuario',
            name='veterinaria',
            field=models.ForeignKey(blank=True, db_column='id_veterinaria', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos_usuario', to='AutenticacionySeguridad.veterinaria'),
        ),
    ]
