# Generated by Django 5.2.12 on 2026-05-04 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionySeguridad', '0006_plansuscripcion_veterinaria_alter_bitacora_options_and_more'),
        ('GestionClientesyMascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='veterinaria',
            field=models.ForeignKey(blank=True, db_column='id_veterinaria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to='AutenticacionySeguridad.veterinaria'),
        ),
    ]
