# Generated by Django 5.2.12 on 2026-04-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionServiciosyReserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='precioservicio',
            name='modalidad',
            field=models.CharField(blank=True, help_text='Modalidad del servicio: Domicilio o Clínica', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='disponible_domicilio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion_estimada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='precioservicio',
            name='variacion',
            field=models.CharField(default='General', help_text='Tamaño de la mascota: Pequeño, Mediano, Grande', max_length=50),
        ),
    ]
