# Generated by Django 5.2.12 on 2026-05-04 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionySeguridad', '0006_plansuscripcion_veterinaria_alter_bitacora_options_and_more'),
        ('GestionServiciosyReserva', '0003_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaservicio',
            name='veterinaria',
            field=models.ForeignKey(blank=True, db_column='id_veterinaria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_servicio', to='AutenticacionySeguridad.veterinaria'),
        ),
        migrations.AddField(
            model_name='cita',
            name='veterinaria',
            field=models.ForeignKey(blank=True, db_column='id_veterinaria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='AutenticacionySeguridad.veterinaria'),
        ),
        migrations.AddField(
            model_name='precioservicio',
            name='veterinaria',
            field=models.ForeignKey(blank=True, db_column='id_veterinaria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precios_servicio', to='AutenticacionySeguridad.veterinaria'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='veterinaria',
            field=models.ForeignKey(blank=True, db_column='id_veterinaria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='AutenticacionySeguridad.veterinaria'),
        ),
    ]
